---
- name: Compress repository
  archive:
    path: ../
    dest: repository.tar.gz

- name: Copy compressed repository to remote machine
  copy:
    src: repository.tar.gz
    dest: /tmp/
 
- name: Extract compressed repository on remote machine
  become: yes
  become_user: root
  archive:
    path: /tmp/repository.tar.gz
    dest: /opt/whanos
  delegate_to: remote_machine

- name: Deploy application using Helm
  command: helm install whanos /opt/whanos/kubernetes/whanos/ --values /opt/whanos/kubernetes/whanos/values.yaml
