---
- name: Copy repository to remote machine
  copy:
    src: ../../../../
    dest: /opt/whanos

- name: Build jenkins image
  shell: cd /opt/whanos && docker build -t localhost:32000/whanos-jenkins . && cd /

- name: Push jenkins image
  shell: docker push localhost:32000/whanos-jenkins

- name: Deploy application using Helm
  command: microk8s helm install jenkins /opt/whanos/kubernetes/whanos/ --values /opt/whanos/kubernetes/whanos/values.yaml

