---
- name: Copy repository to remote machine
  copy:
    src: ../../../../
    dest: /opt/whanos
 
- name: Deploy application using Helm
  command: microk8s helm install whanos /opt/whanos/kubernetes/whanos/ --values /opt/whanos/kubernetes/whanos/values.yaml
