---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Install microk8s
  snap:
    name: microk8s
    state: present
    classic: yes

- name: Add user to Docker and Microk8s groups, they will need to logout and in again
  user:
    name: root
    state: present
    groups:
      - microk8s
    append: true

- name: Add alias to kubectl
  become: false
  lineinfile:
    path: '~/.bashrc'
    regexp: '^alias kubectl='
    line: 'alias kubectl="microk8s kubectl"'
    state: present

- name: Add alias to helm
  become: false
  lineinfile:
    path: '~/.bashrc'
    regexp: '^alias helm='
    line: 'alias helm="microk8s helm"'
    state: present

- name: Sourcing aliases
  shell: . ~/.bashrc