FROM node:14.17.5-alpine

RUN apk add --no-cache bash curl
SHELL ["/bin/bash", "-c"]

RUN npm i befunge93

RUN curl https://gist.githubusercontent.com/0xMemoryGrinder/83f4800c575f3f2506d505c3d7771c58/raw/23acb93fdc02592c4f91ba50ffd83537d32aab00/befunge93Runner.js \
    -o /app/befunge93Runner.js
    
ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD CMD node ./befunge93Runner.js app/main.bf