FROM node:14.17.5-alpine

RUN apk add --no-cache bash curl
SHELL ["/bin/bash", "-c"]

RUN npm i befunge93

RUN curl -L https://gist.githubusercontent.com/0xMemoryGrinder/83f4800c575f3f2506d505c3d7771c58/raw/dcbc9e5493bfb5ec16c8c6e9289bcc4ac05027b4/befunge93Runner.js > /opt/befunge93Runner.js
    
ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD CMD node /opt/befunge93Runner.js /app/main.bf