FROM node:14.17.5-alpine

RUN apk add --no-cache bash curl
SHELL ["/bin/bash", "-c"]

RUN npm i befunge93

COPY befunge93Runner.js /opt/befunge93Runner.js
    
ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD CMD node /opt/befunge93Runner.js /app/main.bf