FROM maven:3.8-openjdk-17-slim as build

SHELL ["/bin/bash", "-c"]

COPY . /app
WORKDIR /app

RUN mvn dependency:resolve -f app/pom.xml \
        && mvn package -f app/pom.xml \
        && cp app/target/app.jar . \


FROM eclipse-temurin:17

SHELL ["/bin/bash", "-c"]

COPY --from=build /app /app
WORKDIR /app

CMD java -jar app.jar