---
- name: Deploy Thanos the wale
  become: yes
  hosts: localhost
  gather_facts: false
  vars:
    repository: "{{ lookup('inventory_hostvars', inventory_hostname)['repository'] }}"
    deploy_directory: "{{ lookup('inventory_hostvars', inventory_hostname)['deploy_directory'] }}"

  roles:
    - base
    - docker
    - jenkins
    - kube
    - whanos


