
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-image
        image: {{ .Values.jenkins.image }}
        ports:
        - name: jenkins-ui-port
          containerPort: 8080
        envFrom:
          - secretRef:
              name: jenkins-secret
      restartPolicy: Always