kind: Service
apiVersion: v1
metadata:
  name:  registry-service
  namespace:  registry
spec:
  selector:
    app:  registry
  type:  ClusterIP
  ports:
  - port:  5000
    protocol: TCP
    targetPort:  5000