apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      restartPolicy: Always
      containers:
        - name: registry
          image: registry:2
          volumeMounts:
            - name: storage
              mountPath: /var/lib/registry
            - name: certs-vol
              mountPath: "/certs"
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:443"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: registry-pvclaim
        - name: certs-vol
          secret:
            secretName: certs-secret