apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: default
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.registry.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvclaim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registry.storage.size }}