---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Install microk8s
  snap:
    name: microk8s
    state: present
    classic: yes

- name: Add user to Docker and Microk8s groups, they will need to logout and in again
  user:
    name: root
    state: present
    groups:
      - docker
      - microk8s
    append: true

- name: Add alias to kubectl
  become: false
  lineinfile:
    path: '/home/.bashrc'
    regexp: '^alias kubectl='
    line: 'alias kubectl="microk8s kubectl"'
    state: present

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: latest
    update_cache: true

- name: Add Helm repository
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: Install Tiller
  become: yes
  become_user: root
  command: helm init --upgrade --service-account tiller
    